import Delegate from "../hooks/delegate"
import Stake from "../hooks/stake"
import Claim from "../hooks/claim"
import UpdateFloor from "../hooks/floor"
import UpdateDistributionEpoch from "../hooks/updateDistributionEpoch"
import UpdateAddressDividends from "../hooks/updateAddressDividends"
import UpdateEpochInheritance from "../hooks/updateAddressInheritance"

export default function Index() {
    return (
        <div>
            <DelegateText />
            <Delegate />
            <StakeText />
            <Stake />
            <ClaimText />
            <Claim />
            <UpdateAddressDividendsText />
            <UpdateAddressDividends />
            <UpdateDistributionEpochText />
            <UpdateDistributionEpoch />
            <UpdateEpochInheritanceText />
            <UpdateEpochInheritance />
            <UpdateFloorText />
            <UpdateFloor />
        </div>
    )
}

function DelegateText() {
    return (
        <section>
            <div className="page-head">
                <img src="./assets/article-banner.png" className="img-fluid" alt="missing"/>
                <h2>Ecosystem gateway</h2>
            </div>
            <div className="container">
                <div className="mt-4 mb-6">
                    <p>Here, you can delegate your voting power which you acquired by having $LIB tokens on your wallet to another wallet 
                        or yourself.<br/>By doing so, you'll be able to participate in Liblock governance by voting if an article should be adopted or not.
                    </p>
                </div>
            </div>
        </section>
    )
}

function StakeText() {
    return (
        <section>
            <div className="container">
                <div className="mt-4 mb-6">
                    <p>Here, you can stake your $LIB tokens.<br/>By doing so, you'll be able to participate in Liblock governance by submitting an article or 
                        simply voting if an article should be adopted or not.<br/>This action will lock your tokens for the period chosen, and will mint $rLIB tokens directly to your wallet.<br/>
                        Note that the $LIB and $rLIB tokens are automatically delegated to you when you stake.
                    </p>
                </div>
            </div>
        </section>
    )
}

function ClaimText() {
    return (
        <section>
            <div className="page-head">
                <img src="./assets/article-banner.png" className="img-fluid" alt="missing"/>
                <h2>Claim</h2>
            </div>
            <div className="container">
                <div className="mt-4 mb-6">
                    <p>Here, you can claim the dividends generated by stacking $LIB and participating in the Liblock ecosystem.</p>
                </div>
            </div>
        </section>
    )
}

function UpdateAddressDividendsText() {
    return (
        <section>
            <div className="container">
                <div className="mt-4 mb-6">
                    <p>With this button, anyone can update a portion of the address dividends obtained during the previous epoch. This proccess must be completed before the next epoch.</p>
                </div>
            </div>
        </section>
    )
}

function UpdateDistributionEpochText() {
    return (
        <section>
            <div className="container">
                <div className="mt-4 mb-6">
                    <p>With this button, anyone can increment the distribution contract epoch when the end period has been crossed. Note that all the previous epoch dividends must have been updated before.</p>
                </div>
            </div>
        </section>
    )
}

function UpdateEpochInheritanceText() {
    return (
        <section>
            <div className="container">
                <div className="mt-4 mb-6">
                    <p>Here, you can inherit your shares still viable from the last epoch to the current one. Anyone can update any address.</p>
                </div>
            </div>
        </section>
    )
}

function UpdateFloorText() {
    return (
        <section>
            <div className="container">
                <div className="mt-4 mb-6">
                    <p>With this button, anyone can update the floor price neccessary to submit a proposal as long as it's been at least 7days since the previous update. This action will also reset the virtual power of every address. </p>
                </div>
            </div>
        </section>
    )
}