import Claim from "../hooks/claim"

export default function Index() {
    return (
        <div>
            <ClaimText />
            <Claim />
        </div>
    )
}

function ClaimText() {
    return (
        <section>
            <div className="page-head">
                <img src="./assets/article-banner.png" className="img-fluid" alt="missing"/>
                <h2>Claim</h2>
            </div>
            <div className="container">
                <div className="mt-4 mb-6">
                    <p>Here, you can claim the dividends generated by stacking $LIB and participating in the Liblock ecosystem.</p>
                </div>
            </div>
        </section>
    )
}